development:
  adapter: postgresql
  encoding: unicode
  database: illusion_database
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: illusion_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: illusion_production
  pool: 5
